{
 "title": "Chrony NTP",
 "tags": [
  "chrony",
  "ntp"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(chrony_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chrony Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chrony_up{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Reference Source",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "chrony_tracking_info{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tracking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "System Clock Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chrony_tracking_last_offset_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "chrony_tracking_rms_offset_seconds{instance=~\"$instance\"}",
     "legendFormat": "RMS Offset"
    }
   ]
  },
  {
   "title": "Stratum",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chrony_tracking_stratum{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Root Delay & Dispersion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_tracking_root_delay_seconds{instance=~\"$instance\"}",
     "legendFormat": "Root Delay"
    },
    {
     "expr": "chrony_tracking_root_dispersion_seconds{instance=~\"$instance\"}",
     "legendFormat": "Root Dispersion"
    }
   ]
  },
  {
   "title": "Frequency & Skew",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "chrony_tracking_frequency_ppms{instance=~\"$instance\"}",
     "legendFormat": "Frequency Error"
    },
    {
     "expr": "chrony_tracking_skew_ppms{instance=~\"$instance\"}",
     "legendFormat": "Skew"
    },
    {
     "expr": "chrony_tracking_residual_frequency_ppms{instance=~\"$instance\"}",
     "legendFormat": "Residual Frequency"
    }
   ]
  }
 ]
}